import React from 'react';
import { CompanyProfile, ReconciliationRecord } from '../../types/finance';
import { formatINR } from '../../utils/formatters';
import { X, Download, ShieldCheck, Printer, CheckCircle } from 'lucide-react';

interface AuditReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  company: CompanyProfile;
  records: ReconciliationRecord[];
}

export const AuditReportModal: React.FC<AuditReportModalProps> = ({
  isOpen,
  onClose,
  company,
  records,
}) => {
  if (!isOpen) return null;

  const totalGross = records.reduce((sum, r) => sum + r.gatewayGrossINR, 0);
  const totalMdr = records.reduce((sum, r) => sum + r.gatewayMdrINR, 0);
  const totalBank = records.reduce((sum, r) => sum + r.bankCreditINR, 0);

  const downloadCSV = () => {
    const headers = ['Record ID', 'Order ID', 'Payment ID', 'Invoice #', 'Gateway Gross (INR)', 'MDR Fee (INR)', 'Bank Credit (INR)', 'Variance (INR)', 'Status', 'Resolution'];
    const rows = records.map(r => [
      r.id,
      r.orderId,
      r.paymentId || '',
      r.invoiceNumber || '',
      r.gatewayGrossINR,
      r.gatewayMdrINR,
      r.bankCreditINR,
      r.varianceINR,
      r.status,
      r.resolutionStatus,
    ]);

    const csvContent = [headers.join(','), ...rows.map(row => row.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `Razorpay_Reconciliation_Audit_${company.id}_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-sm p-4">
      <div className="w-full max-w-3xl rounded-xl border border-[#E2DFD8] bg-[#111726] p-6 shadow-xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-start justify-between border-b border-[#E2DFD8] pb-4">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#F7F6F2] text-[#1C2331]">
              <ShieldCheck className="h-4 w-4" />
            </div>
            <div>
              <h2 className="text-sm font-semibold text-slate-100">3-Way Reconciliation Audit Summary</h2>
              <p className="text-xs text-[#5E6C84]">Generated by Razorpay LedgerMind AI Controller</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-md p-1.5 text-[#5E6C84] hover:bg-[#F7F6F2] hover:text-[#1C2331] transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Certificate Body */}
        <div className="mt-5 rounded-lg border border-[#E2DFD8] bg-[#0D131F] p-4 space-y-4">
          <div className="flex justify-between items-center border-b border-[#E2DFD8] pb-3 text-xs">
            <div>
              <span className="text-[#5E6C84]">Entity:</span> <strong className="text-[#1C2331]">{company.legalEntity}</strong>
            </div>
            <div>
              <span className="text-[#5E6C84]">GSTIN:</span> <span className="font-mono text-[#1C2331]">{company.gstin}</span>
            </div>
            <div>
              <span className="text-[#5E6C84]">MID:</span> <span className="font-mono text-[#1C2331]">{company.razorpayMid}</span>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-3 text-center text-xs">
            <div className="bg-slate-950 p-3 rounded border border-[#E2DFD8]/80">
              <div className="text-[#5E6C84] uppercase text-[10px]">Total Gateway Gross</div>
              <div className="text-sm font-bold text-slate-100 font-mono mt-1">{formatINR(totalGross)}</div>
            </div>
            <div className="bg-slate-950 p-3 rounded border border-[#E2DFD8]/80">
              <div className="text-[#5E6C84] uppercase text-[10px]">Total MDR Fees + GST</div>
              <div className="text-sm font-bold text-slate-100 font-mono mt-1">{formatINR(totalMdr)}</div>
            </div>
            <div className="bg-slate-950 p-3 rounded border border-[#E2DFD8]/80">
              <div className="text-[#5E6C84] uppercase text-[10px]">Net Bank Settled</div>
              <div className="text-sm font-bold text-slate-100 font-mono mt-1">{formatINR(totalBank)}</div>
            </div>
          </div>

          <div className="text-xs text-[#1C2331] leading-relaxed bg-slate-950 p-3 rounded border border-[#E2DFD8]/80">
            <p>
              This certifies that <strong>{records.length} settlement batches</strong> have been verified against Razorpay Gateway API logs, ICICI/HDFC Bank statement credits, and ERP sales invoices.
            </p>
            <p className="mt-2 text-[#1C2331] flex items-center gap-1.5 font-medium">
              <CheckCircle className="h-3.5 w-3.5 text-emerald-500" />
              All variances have been reconciled with corresponding double-entry journal adjustments.
            </p>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="mt-5 flex items-center justify-between border-t border-[#E2DFD8] pt-4">
          <span className="text-[11px] text-[#5E6C84] font-mono">Audit Hash: SHA256:7f88a91b...</span>
          <div className="flex gap-2">
            <button
              onClick={() => window.print()}
              className="flex items-center gap-1.5 rounded-lg border border-[#E2DFD8] bg-[#F7F6F2] px-3 py-1.5 text-xs font-medium text-[#1C2331] hover:bg-[#E2DFD8] transition-colors"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={downloadCSV}
              className="flex items-center gap-1.5 rounded-lg bg-blue-600 px-3.5 py-1.5 text-xs font-medium text-white hover:bg-blue-500 transition-colors shadow-sm"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Export CSV</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
